create_tags: patch
do_version_commit: true
master: main
patch_prefix: .
preserve_patch_zero: truej
push_master: true
push_tags: true
remote: origin
version_file: .web_package/config.yml
version: 0.0.6
